/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as TvshowsAiringtodayImport } from './routes/tvshows.airingtoday'
import { Route as MoviesNowplayingImport } from './routes/movies.nowplaying'

// Create Virtual Routes

const IndexLazyImport = createFileRoute('/')()

// Create/Update Routes

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const TvshowsAiringtodayRoute = TvshowsAiringtodayImport.update({
  path: '/tvshows/airingtoday',
  getParentRoute: () => rootRoute,
} as any)

const MoviesNowplayingRoute = MoviesNowplayingImport.update({
  path: '/movies/nowplaying',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/movies/nowplaying': {
      id: '/movies/nowplaying'
      path: '/movies/nowplaying'
      fullPath: '/movies/nowplaying'
      preLoaderRoute: typeof MoviesNowplayingImport
      parentRoute: typeof rootRoute
    }
    '/tvshows/airingtoday': {
      id: '/tvshows/airingtoday'
      path: '/tvshows/airingtoday'
      fullPath: '/tvshows/airingtoday'
      preLoaderRoute: typeof TvshowsAiringtodayImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexLazyRoute,
  MoviesNowplayingRoute,
  TvshowsAiringtodayRoute,
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/movies/nowplaying",
        "/tvshows/airingtoday"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/movies/nowplaying": {
      "filePath": "movies.nowplaying.tsx"
    },
    "/tvshows/airingtoday": {
      "filePath": "tvshows.airingtoday.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
