/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as DiscoverNowplayingImport } from './routes/discover.nowplaying'

// Create Virtual Routes

const IndexLazyImport = createFileRoute('/')()

// Create/Update Routes

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const DiscoverNowplayingRoute = DiscoverNowplayingImport.update({
  path: '/discover/nowplaying',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/discover/nowplaying': {
      id: '/discover/nowplaying'
      path: '/discover/nowplaying'
      fullPath: '/discover/nowplaying'
      preLoaderRoute: typeof DiscoverNowplayingImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexLazyRoute,
  DiscoverNowplayingRoute,
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/discover/nowplaying"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/discover/nowplaying": {
      "filePath": "discover.nowplaying.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
